Create windows install workflow
azavea/pwd-fishway pull request #126
Opened 2019-07-30 20:15 UTC by fungjj92

## Overview

Use this pipeline to install the app to the Windows computer. For app updates we'll probably send the zip file to the museum tech consultants, Greenhouse, but may also have to run over to the museum to do an install.

Connects #76

## Testing Instructions

Run `./scripts/cipublish` locally from within the VM and see the project zips up all its built assets and the app runs correctly from the `index.html` file. 

Currently a stale version is hosted on the Windows computer from `localhost` root and it'll be updated when we're ready to ship! 🚢🚀

2019-08-02 16:00 UTC, caseycesari requested changes
Working well, but I think the `zip` install needs to be moved to Ansible to ensure if we move the build to CI, the script won't be halted by problems installing it via `apt-get` (like waiting for the user to type `Y` to verify the install, or problems with `sudo`)

2019-08-02 16:00 UTC, caseycesari commented on scripts/cipublish
> +    sudo apt-get install zip
Consider installing this via an Ansible role. The parcel viewer does this, for example. https://github.com/azavea/pwd-parcel-viewer/tree/develop/deployment/ansible/roles

2019-08-02 16:00 UTC, caseycesari commented on scripts/cipublish
> +    zip -r ../../../fishway.zip ./*
Consider storing this in `dist`, which is used for other built output.

2019-08-05 20:23 UTC, fungjj92 commented on scripts/cipublish
> +    sudo apt-get install zip
Ah, this is good advice!

2019-08-05 20:32 UTC, fungjj92 commented
I've made the suggested changes and tested the zip output on the Windows machine -- thanks for those!

2019-08-06 15:10 UTC, caseycesari commented
Taking another look.

2019-08-06 15:25 UTC, caseycesari approved these changes
Looks good!

2019-08-06 17:08 UTC, merged

2019-08-06 17:08 UTC, fungjj92 commented
Thank you for review! Merged.