Apply transition to tab navigation
azavea/pwd-fishway pull request #129
Opened 2019-08-05 19:25 UTC by fungjj92

## Overview

See the commit message for detail. To get tabs transitions set up for design, lift the `Fade` transition included in React-Bootstrap.

Connects #123

### Demo

![transition](https://user-images.githubusercontent.com/10568752/62488914-73a85d00-b793-11e9-8af8-7acbfca62e7a.gif)

### Notes

I didn't find any CSS for the `Fade` transition in the library 🤔 I added our own in `globalStyle`, which hooked into the classes applied via the transition.

## Testing Instructions

Ensure the netlify site behaves as before, plus transitions between tabs.

2019-08-06 15:33 UTC, caseycesari requested changes
Not sure why this is happening, but it appears to be caused by the changes on this PR. I tested the previous deploy preview, and couldn't reproduce it. 

When switching between tabs, the video content extends outside of its area and overlaps with the tabs. Sometimes initially it is contained, but then switching back and forth causes it to pop out.

![Aug-06-2019 11-30-49](https://user-images.githubusercontent.com/1042475/62553770-f0901100-b83d-11e9-81ab-f4fda3b4d4fd.gif)

2019-08-07 14:10 UTC, fungjj92 commented
Weird behavior! On my local instance at 1920x1080 res, I clicked back and forth between X tab back to Meet The Fish dozens of times and was not able to reproduce that issue. Can you provide more detail about how you got this issue?

2019-08-07 15:06 UTC, alexelash commented
@fungjj92 @caseycesari Just tested my local on the ELO and didn't see the strange layout issues 🤷‍♀️

@fungjj92 We talked about this offline, but I'll need to set up custom transitions for at least the Meet The Fish page, where the fish will slide in from the right-hand side (to hide the loading issue). This particular animation (which is probably the most important) can be done with CSS transitions, so long as I have a specific classname to attach to, e.g. `.tab-content--meet-the-fish` 

Is this currently working in this branch, and if not could it be added? I didn't see it anywhere but I could be missing it.

2019-08-07 16:16 UTC, caseycesari commented
Tried it locally as well as on Netlify, and it happens in both instances. It's triggered just by switching through the tabs. 

My screen resolution was 1280 x 800. I kicked it up to 1680 x 1050 and the problem went away. If that is closer to the actual display, then this might not be an issue.

2019-08-07 19:28 UTC, fungjj92 commented
@caseycesari  I think it may be a non-issue, the app will only be used on the ELO at 1920x1080. 🤞 

@alexelash Thanks for raising that -- 8555bbb adds that for ya. You'll have to write your own custom transition, but there's a template in `Fade.js` that you can copy into a new file and customize!

2019-08-08 16:38 UTC, caseycesari approved these changes

2019-08-08 16:46 UTC, merged