Add quiz view
azavea/pwd-fishway pull request #59
Opened 2019-05-08 18:47 UTC by fungjj92

## Overview

When the user elects to play the quiz, the user is dropped into a fullscreen quiz outside the framework of the 4 tabs. When the quiz is exited, whether by finishing or closing out, we still want to return to the user to the quiz tab and previous app state. This PR adds the quiz view and implements that behavior.

Connects #40 

### Demo

![quizinternal](https://user-images.githubusercontent.com/10568752/57399718-d2176c80-719f-11e9-9c99-5a0a13f8bb8e.gif)

### Notes

Our root folder is growing with components, so I organized them into a `components` subdirectory. We may want a separate folder for styled-components.

## Testing Instructions

 * How to test this PR
 * Prefer bulleted description
 * Start after checking out this branch
 * Include any setup required, such as bundling scripts, restarting services, etc.
 * Include test case, and expected output

2019-05-09 15:18 UTC, maurizi requested changes
Great to see the reorganization in https://github.com/azavea/pwd-fishway/pull/59/commits/9f624453c9a22e299e7d53bf6defb6f9ffdab881, that was sorely needed.

Functionally this is good.
I left a few comments re: readability that I'd like to see addressed unless you have strong objections.

2019-05-09 15:18 UTC, maurizi commented on src/app/src/App.js
> +                {!isScreensaverVisible && app}
Consider using a ternary operator here, and grouping the two `!isScreensaverVisible` components, to make the control flow more explicit:
```jsx
<div className='App'>
    <GlobalStyle />
    {isQuizVisible && quiz}
    {isScreensaverVisible ? (
        screensaver
    ) : (
        <>
            {idleTimer}
            {app}
        </>
    )}
</div>
```

2019-05-09 15:18 UTC, maurizi commented on src/app/src/components/Navbar.js
> +        // from About tab to another tab and back again
Can we move this comment down a line, so it remains above the line it relates to?

2019-05-09 15:18 UTC, maurizi commented on src/app/src/components/Quiz.js
> +const StyledQuiz = styled(Box)``;
There isn't a need to have a named `StyledQuiz` if we aren't styling it yet - we can directly use `Box` for now.

2019-05-09 15:18 UTC, maurizi commented on src/app/src/components/QuizNavbar.js
> +const CloseButton = styled(Button)``;
Similar to above, there isn't a need to have a named `CloseButton` if we aren't styling it yet - we can directly use `Button` for now.

2019-05-09 17:28 UTC, fungjj92 commented on src/app/src/App.js
> +                {!isScreensaverVisible && app}
Additionally I moved the ternary outside of the return JSX to keep that code cleaner.

2019-05-09 17:30 UTC, maurizi commented on src/app/src/components/Navbar.js
> +            switching // from About tab to another tab and back again */}
```suggestion
            switching from About tab to another tab and back again */}
```

2019-05-09 17:32 UTC, fungjj92 commented on src/app/src/components/Navbar.js
> +            switching // from About tab to another tab and back again */}
🤦‍♀

2019-05-09 19:41 UTC, maurizi approved these changes
🎉 looks good!

2019-05-10 13:16 UTC, fungjj92 commented
Thanks for reviews! :D

2019-05-10 13:16 UTC, merged